[ 2025-02-06 23:22:36,508 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.17:5000
[ 2025-02-06 23:22:36,509 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-02-06 23:22:50,409 ] 97 werkzeug - INFO - 192.168.1.17 - - [06/Feb/2025 23:22:50] "GET / HTTP/1.1" 200 -
[ 2025-02-06 23:22:51,558 ] 97 werkzeug - INFO - 192.168.1.17 - - [06/Feb/2025 23:22:51] "GET /home HTTP/1.1" 200 -
[ 2025-02-06 23:22:59,762 ] 875 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py", line 17, in predict
    data_scaled = preprocessor.transform(features)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1090, in transform
    raise ValueError(f"columns are missing: {diff}")
ValueError: columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 59, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py", line 22, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py] line number [17] error message[columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 63, in predict_datapoint
    raise CustomException(e,sys)
src.exception.CustomException: Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\app.py] line number [59] error message[Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py] line number [17] error message[columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}]]
[ 2025-02-06 23:22:59,790 ] 97 werkzeug - INFO - 192.168.1.17 - - [06/Feb/2025 23:22:59] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-02-06 23:23:03,937 ] 97 werkzeug - INFO - 192.168.1.17 - - [06/Feb/2025 23:23:03] "GET /home HTTP/1.1" 200 -
[ 2025-02-06 23:23:12,639 ] 875 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py", line 17, in predict
    data_scaled = preprocessor.transform(features)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1090, in transform
    raise ValueError(f"columns are missing: {diff}")
ValueError: columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 59, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py", line 22, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py] line number [17] error message[columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 63, in predict_datapoint
    raise CustomException(e,sys)
src.exception.CustomException: Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\app.py] line number [59] error message[Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\src\pipeline\predict_pipeline.py] line number [17] error message[columns are missing: {'Irrigation System Type', 'Soil Type', 'Rainfall (mm)', 'Temperature (°C)', 'Terrain Type', 'Water Availability', 'Humidity (%)', 'Wind Speed (km/h)', 'Sunlight Hours', 'Evapotranspiration (mm/day)', 'Crop Type', 'Soil Moisture (%)', 'Rainfall Forecast (mm)', 'Vegetation Index', 'Distance to Water Source (km)', 'Recommended Irrigation Level', 'Irrigation Frequency (days)'}]]
[ 2025-02-06 23:23:12,642 ] 97 werkzeug - INFO - 192.168.1.17 - - [06/Feb/2025 23:23:12] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
